### ISSUE TITLE
template 启动的时候不是应该写是App吗?

### ISSUE THREAD

**Issue by pkptzx** [Surrealism-All/slimk-template#1]
```
cargo generate --git https://github.com/Surrealism-All/surrealism-ui-template.git --name {project_name}
cargo r
```
运行失败,查看代码发现这里应该是App吧?不应该是APPWindow吧?

https://github.com/Surrealism-All/surrealism-ui-template/blob/4ecd0c800e2721c4b424fc9169c3dd9238752123/src/main.rs#L4

我改为App后运行正常

**Comment by syf20020816** [comment]
目前最新版本已修复
